### ISSUE TITLE
Disclaim of copyright for vmod template?

### ISSUE THREAD

**Issue by sodabrew** [varnish/libvmod-example#1]
Would you guys consider a disclaimer of copyright or a copyright exception clause for a template vmod upon which others should be based?

If I can directly fork this repo to begin work on my own vmod, using this one as a template for the autogen / configure / m4 / src tree layout, I'd like apply my own copyright rather than inherit from the Varnish copyright.

Looking at some of the downstream forks of this repo, others are treating the LICENSE file as a template where Varnish Software AS can be replaced with Other Org. I think that's the right direction to go in, but it isn't explicitly permitted.

**Comment by lkarsten** [comment]
See also #12 for further developments on licensing.
