### ISSUE TITLE
relax license

### ISSUE THREAD

**Issue by nigoroll** [varnish/libvmod-example#12]
just a reminder -- as discussed on IRC, I think relaxing the license of libvmod-example (for instance to stating that it is in the public domain) would help VMOD authors with doubts of their legal departments

irc

(12:56:23) scn: i don't think we have anything to gain by mandating a license on it
(12:57:32) slink: scn: yeah. How about "libvmod-example is in the public domain"?
(12:57:35) scn: and copyright .. they get their own when they make a derivative work, don't they?
(12:58:05) slink: scn: yes, but in the strict sense one had to keep the copyright for any code stemming from libvmod-example
(12:58:45) scn: i don't know why we have all of that stuff in there in the first place. before my time. i'm ok with simplifying it.

**Comment by perbu** [comment]
I don't mind it being PD.

**Comment by perbu** [comment]
It would however be nice if they pointed to the example vmod on Github without it being a strict requirement. Just so people know.

**Comment by fgsch** [comment]
What about http://unlicense.org/ ?

**Comment by perbu** [comment]
Sure. Looks fine.

On Mon, Mar 2, 2015 at 2:56 PM, Federico G. Schwindt <
notifications@github.com> wrote:

> What about http://unlicense.org/ ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/varnish/libvmod-example/issues/12#issuecomment-76715028>
> .
>



-- 
*Per Buer*
CTO | Varnish Software AS
Cell: +47 95839117
We Make Websites Fly!
www.varnish-software.com
[image: Register now]
<http://info.varnish-software.com/varnish-summits-autumn-2014-registration>

**Comment by lkarsten** [comment]
Implemented in 3.0, 4.0 and master. Closing issue.

**Comment by lkarsten** [comment]
Federico insisted that we should remove the copyright notice as well.

IMHO (IANAL and so on) that does not make any difference, since the authors implicitly have copyright these days, but perhaps it is less confusing to someone using this for the first time.

**Comment by perbu** [comment]
We won't claim any copyright over this. We should of course list authors
but to be perfectly clear we don't have to have a copyright claim.

On Tue, Mar 3, 2015 at 4:44 PM, Lasse Karstensen <notifications@github.com>
wrote:

> Federico insisted that we should remove the copyright notice as well.
>
> IMHO (IANAL and so on) that does not make any difference, since the
> authors implicitly have copyright these days, but perhaps it is less
> confusing to someone using this for the first time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/varnish/libvmod-example/issues/12#issuecomment-76970059>
> .
>



-- 
*Per Buer*
CTO | Varnish Software AS
Cell: +47 95839117
We Make Websites Fly!
www.varnish-software.com
[image: Register now]
<http://info.varnish-software.com/varnish-summits-autumn-2014-registration>

**Comment by fgsch** [comment]
I'm not a lawyer but putting this in the public domain and having a copyright in there makes no sense to me. Listing authors OTOH is perfectly fine.
I looked at sqlite and youtube-dl, the latter using unlicense, and i cannot find any copyright.
