### ISSUE TITLE
need to use the same varnishd and varnishtest as building against

### ISSUE THREAD

**Issue by nigoroll** [varnish/libvmod-example#13]
configure prefers varnishd/varnishtest from $PATH over those from directories from the pkg-config, so libvmod-example may end up building against a different installation than the one used for `make check`
```shell
$ PATH=/usr/sbin:$PATH
$ PKG_CONFIG_PATH=/tmp/lib/pkgconfig ./configure
...
checking for varnishtest... /usr/bin/varnishtest
checking for varnishd... /usr/sbin/varnishd
```
but:
```shell
$ PKG_CONFIG_PATH=/tmp/lib/pkgconfig pkg-config --variable=sbindir varnishapi
/tmp/sbin
$ PKG_CONFIG_PATH=/tmp/lib/pkgconfig pkg-config --variable=bindir varnishapi
/tmp/bin
$ ls -als /tmp/sbin/varnishd /tmp/bin/varnishtest 
 360 -rwxr-xr-x 1 slink slink  366600 Mar  3 17:45 /tmp/bin/varnishtest
2632 -rwxr-xr-x 1 slink slink 2692576 Mar  3 17:45 /tmp/sbin/varnishd
```

this can be worked around by passing the `VARNISHD` and `VARNISHTEST` variables to `configure` pointing to the right paths.

I will prepare a fix and issue a pull request.

**Comment by lkarsten** [comment]
Should be solved now that with @nigoroll 's pull requests are merged.
