### ISSUE TITLE
autoconf on el6 fails

### ISSUE THREAD

**Issue by lkarsten** [varnish/libvmod-example#16]
```
[lkarsten@el6 libvmod-example]$ ./autogen.sh 
++ pkg-config --variable=datarootdir varnishapi
+ dataroot=/usr/share
+ aclocal -I m4 -I /usr/share/aclocal
configure.ac:1: error: Autoconf version 2.64 or higher is required
configure.ac:1: the top level
autom4te: /usr/bin/m4 failed with exit status: 63
aclocal: autom4te failed with exit status: 63

```

**Comment by nigoroll** [comment]
should be done with the latest pull request

**Comment by nigoroll** [comment]
to those receiving email updates: my previous comment was wrong and I have deleted it.

**Comment by nigoroll** [comment]
@fgsch pointed out in #18 that this smells like requiring the same fix as https://github.com/varnish/Varnish-Cache/commit/ecfc75783bcfc906a0a5be77f3c93e3a0dfe7a4c but as this was applied to varnish.m4, we should not require it in libvmod-example.
So I'd presume all that needs to be done is to set `AC_PREREQ(2.59)` as in varnish configure.ac
