### ISSUE TITLE
configure fails on systems with older pkg-config

### ISSUE THREAD

**Issue by nigoroll** [varnish/libvmod-example#19]
The PKG_CHECK_VAR macro was added to pkg.m4 with commit 5b463c927b6caeb332bb147572ea82b1650ceb7d of git://anongit.freedesktop.org/pkg-config, which went into pkg-config-0.28

Thus, on systems with pkg-config <= 0.27, PKG_CHECK_VAR is not available and autoconf fails.

**Comment by lkarsten** [comment]
Merged. Thanks.
